### ISSUE TITLE
Conseil : utiliser JAVA ou autre

### ISSUE THREAD

**Issue by flodavid** [ThibautRoperch/MoteurInferenceZeroPlus#1]
C'est l'un des rares projets de M1 où on a le choix du langage, après c'est bien souvent soit C++, soit C, car la performance est importante en Optimisation par exemple

**Comment by ThibautRoperch** [comment]
Interface graphique en JAVA, on n'a pas appris ! Et le jour des soutenances de projet l'année dernière, un groupe s'était fait taper sur les doigts car ils avaient fait leur interface graphique en JAVA alors qu'on a appris à faire du Qt toute l'année

**Comment by flodavid** [comment]
C'est Amghar ! Et c'est pas un projet de fait d'année qui permet de valider les compétences.
De plus, pas besoin d'interface graphique, c'est pas du tout le coeur du projet
